apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: youtube-app
          image: nandhulal0499/youtube-app:new
          ports:
            - containerPort: 3000  # Your Node.js application should listen on port 3000
